name: Backup Job

on:
  schedule:
    - cron: '*/5 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: [4.4]

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: mongo to drive
        env:
          DB: ${{ secrets.DB }}
          G_DRIVE_CLIENT_ID: ${{ G_DRIVE_CLIENT_ID }}
          G_DRIVE_CLIENT_SECRET: ${{ G_DRIVE_CLIENT_SECRET }}
          G_DRIVE_REDIRECT_URIS: ${{ G_DRIVE_REDIRECT_URIS }}
          G_DRIVE_ACCESS_TOKEN: ${{ G_DRIVE_ACCESS_TOKEN }}
          G_DRIVE_REFRESH_TOKEN: ${{ G_DRIVE_REFRESH_TOKEN }}
          G_DRIVE_TOKEN_EXPIRY_DATE: ${{ G_DRIVE_TOKEN_EXPIRY_DATE }}
          G_DRIVE_BACKUP_FOLDER_ID: ${{ G_DRIVE_BACKUP_FOLDER_ID }}
        run: npm start
